spring.application.name=EBANK-BOT
server.port=8058

management.endpoints.web.exposure.include=health

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.client.jersey.enabled=false

spring.ai.openai.api-key=${OPENAI_API_KEY}

discord.token=${DISCORD_TOKEN:}
discord.gateway-intents=MESSAGE_CONTENT,GUILD_MESSAGES,DIRECT_MESSAGES

spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.streamable-http.connections.customer-service.url=http://localhost:8056
spring.ai.mcp.client.streamable-http.connections.customer-service.endpoint=/mcp
spring.ai.mcp.client.streamable-http.connections.ebank-service.url=http://localhost:8057
spring.ai.mcp.client.streamable-http.connections.ebank-service.endpoint=/mcp
